version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - '3301:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Fenix1985
      MYSQL_DATABASE: application_main
      MYSQL_USER: fenix
      MYSQL_PASSWORD: "Fenix1985"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
  be-app:
    image: be-app
    container_name: "be-app"
    restart: always
    ports:
      - "8088:80"
    environment:
    #  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/application_main?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_JDBC-URL: jdbc:mysql://mysql-db:3306/application_main?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Fenix1985"

      APP.DATASOURCE.CANELIA.JDBC-URL: jdbc:mysql://mysql-db:3306/application_canelia?autoReconnect=true&useSSL=false
      APP.DATASOURCE.CANELIA.USERNAME: root
      APP.DATASOURCE.CANELIA.PASSWORD: "Fenix1985"

      APP.DATASOURCE.OVOFRAIS.JDBC-URL: jdbc:mysql://mysql-db:3306/application_ovofrais?autoReconnect=true&useSSL=false
      APP.DATASOURCE.OVOFRAIS.USERNAME: root
      APP.DATASOURCE.OVOFRAIS.PASSWORD: "Fenix1985"

      APP.DATASOURCE.FRAISCAPRICES.JDBC-URL: jdbc:mysql://mysql-db:3306/application_fraiscaprices?autoReconnect=true&useSSL=false
      APP.DATASOURCE.FRAISCAPRICES.USERNAME: root
      APP.DATASOURCE.FRAISCAPRICES.PASSWORD: "Fenix1985"


    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - db

