version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: appsDB
    restart: always
    ports:
      - '3301:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Fenix1985
      MYSQL_DATABASE: application_db
      MYSQL_USER: fenix
      MYSQL_PASSWORD: Fenix1985


  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
        
     
